### ----------------------------- ###
### ----- SOLVER PROPERTIES ----- ###
### ----------------------------- ###
[solver.equation]
    # Specify the solver to use. Available solvers are:
    # heatDiffusion, pressureProjection
    solver = 'pressureProjection'

[solver.fluid]
    # kinematic viscosity
    nu = 1e-2

    # density
    rho = 1.0

[solver.time]
    # time step (only used if CFLBasedTimeStepping is set to false)
    dt  = 1.0

    # number of time steps to perform
    timesteps = 100

[solver.schemes]
    # time-integration scheme to use. Available schemes are:
    # firstOrderEuler, secondOrderBackwards
    timeIntegrationScheme = 'secondOrderBackwards'

    # non-linear scheme to use. Available schemes are:
    # firstOrderUpwind, secondOrderUpwind
    nonLinearScheme = 'firstOrderUpwind'

    # diffusion scheme to use. Available schemes are:
    # secondOrderCentral
    diffusionScheme = 'secondOrderCentral'

[solver.linearSolver]
    # Linear solver for the implicit treatment. Available solvers are:
    # RICHARDSON, CG, BCGS, GMRES
    solver = {u = "BCGS", v="BCGS", p="BCGS"}

    # Preconditioner for the implicit treatment. Available preconditioners are:
    # JACOBI, ILU, SOR, GAMG, NONE
    preconditioner = {u = "ILU", v="ILU", p="ILU"}

    # relative tolerance to reach for the linear solver within each time step
    tolerance = {u = 1e-10, v = 1e-10, p = 1e-10}

    # max allowable iterations by the implicit solver
    maxIterations = {u = 1000, v = 1000, p = 1000}

    # under-relaxation factor for the implicit solver
    underRelaxation = {u = 1.0, v = 1.0, p = 1.0}

[solver.convergence]
    # number of picard iterations
    picardIterations = 10

    # residual tolerance for picard iteration convergence
    picard_tolerance = {u = 1e-3, v = 1e-3, p = 1e-3}

    # residual tolerance for the overall simulation
    convergence_tolerance = {u = 1e-8, v = 1e-8, p = 1e-8}

[solver.output]
    # filename used to write out the solution
    filename = "channel"

    # write output file every X time steps (set to 0 if no animation should be written)
    writingFrequency = 0

### --------------------------- ###
### ----- MESH PROPERTIES ----- ###
### --------------------------- ###
[mesh.block1]
    # start/end location and number of points to use in the x direction
    x = {start = 0.0, end = 10.0, num = 51}

    # start/end location and number of points to use in the y direction
    y = {start = 0.0, end = 1.0, num = 21}

### ------------------------------------------ ###
### ----- BOUNDARY CONDITIONS PROPERTIES ----- ###
### ------------------------------------------ ###
[boundaryCondition.block1]
    # boundary conditions in the east direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    east =  {u = {type = "neumann", value = 0.0}, v = {type = "neumann", value = 0.0}, p = {type = "dirichlet", value = 0.0}}

    # boundary conditions in the west direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    west =  {u = {type = "dirichlet", value = 1.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}

    # boundary conditions in the north direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    north = {u = {type = "dirichlet", value = 0.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}

    # boundary conditions in the south direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    south = {u = {type = "dirichlet", value = 0.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}