### ----------------------------- ###
### ----- SOLVER PROPERTIES ----- ###
### ----------------------------- ###
[solver.equation]
    # Specify the solver to use. Available solvers are:
    # heatDiffusion, pressureProjection
    solver = 'heatDiffusion'

[solver.fluid]
    # thermal expansion coefficient
    alpha = 1e-3

[solver.time]
    # use CFL based time stepping
    CFLBasedTimeStepping = false

    # CFL number (only used if CFLBasedTimeStepping is set to true)
    CFL = 0.25

    # time step (only used if CFLBasedTimeStepping is set to false)
    dt  = 10.0

    # end time of the simulation
    endTime = 500.0

[solver.linearSolver]
    # Linear solver for the implicit treatment. Available solvers are:
    # RICHARDSON, CG, BCGS, GMRES
    solver = {T = "GMRES"}

    # Preconditioner for the implicit treatment. Available preconditioners are:
    # JACOBI, ILU, SOR, NONE
    preconditioner = {T = "ILU"}

    # relative tolerance to reach for the linear solver within each time step
    tolerance = {T = 1e-8}

    # max allowable iterations by the implicit solver
    maxIterations = {T = 1000}

    # number of picard iterations
    picardIterations = 1

[solver.convergence]
    # residual tolerance for picard iteration convergence
    picard_tolerance = {T = 1}

    # residual tolerance for the overall simulation
    convergence_tolerance = {T = 1e-10}

[solver.output]
    # filename used to write out the solution
    filename = "heatedCavity"

    # write output file every X time steps
    writingFrequency = 10

### --------------------------- ###
### ----- MESH PROPERTIES ----- ###
### --------------------------- ###
[mesh.block1]
    # start/end location and number of points to use in the x direction
    x = {start = 0.0, end = 1.0, num = 41}

    # start/end location and number of points to use in the y direction
    y = {start = 0.0, end = 1.0, num = 41}

### ------------------------------------------ ###
### ----- BOUNDARY CONDITIONS PROPERTIES ----- ###
### ------------------------------------------ ###
[boundaryCondition.block1]
    # boundary conditions in the east direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    east =  {T = {type = "dirichlet", value = 0.0}}

    # boundary conditions in the west direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    west =  {T = {type = "dirichlet", value = 0.0}}

    # boundary conditions in the north direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    north = {T = {type = "dirichlet", value = 1.0}}

    # boundary conditions in the south direction. Available boundary conditions are:
    # dirichlet, neumann, interface
    south = {T = {type = "dirichlet", value = 0.0}}