[block1]
x = {start = 0.0, end = 0.5, num = 21}
y = {start = 0.0, end = 0.5, num = 21}

[block2]
x = {start = 0.5, end = 1.0, num = 21}
y = {start = 0.0, end = 0.5, num = 21}

[block3]
x = {start = 0.0, end = 0.5, num = 21}
y = {start = 0.5, end = 1.0, num = 21}

[block4]
x = {start = 0.5, end = 1.0, num = 21}
y = {start = 0.5, end = 1.0, num = 21}