[fluid]
nu = 1e-3
alpha = 1e-3

[time]
CFLBasedTimeStepping = false
CFL = 10.0
dt  = 10.0
endTime = 500.0

[linearSolver]
tolerance = {T = 1e-8}
maxIterations = {T = 1000}

[output]
filename = "heatedCavity"
